version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 12
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build $S3_BUCKET
      - HTML=$(cat ./build/index.html | base64)
      - echo "{\"endpoint\":\"$REACT_ENDPOINT\",\"data\":\"$HTML\"}";
      - curl "https://dev81833.service-now.com/api/now/table/incident?sysparm_limit=1" --request GET --header "Accept:application/json" --user $SERVICENOW_USERNAME:$SERVICENOW_PASSWORD
     

