version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 12
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install 
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - HTML=$(cat ./build/index.html | base64); PAYLOAD="{\"endpoint\":\"${REACT_ENDPOINT}\",\"data\":\"${HTML}\"}"; echo $PAYLOAD > ./build/payload.json;   
      - aws s3 sync ./build $S3_BUCKET
      - echo $HTML;
      - curl --header "Accept:application/json" --header "Content-Type:application/json" -d "@./build/payload.json" --user $SERVICENOW_USERNAME:$SERVICENOW_PASSWORD -X POST $DEPLOYMENT_ENDPOINT 
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths $INVALIDATION_PATHS
