version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 12
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build $S3_BUCKET
      - HTML=$(cat ./build/index.html); curl -i -X POST -u $SERVICENOW_AUTH -H "Content-Type:application/json" -d "{\"endpoint\":\"$REACT_ENDPOINT\",\"data\":\"$HTML\"}" $DEPLOYMENT_ENDPOINT

